apiVersion: eksctl.io/v1
kind: ClusterConfig
metadata:
  name: eksdemo1
  region: eu-central-1
  version: '1.21'

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-0fcaed4ab8d710574 }
      eu-central-1b: { id: subnet-043f7d85b8ef5ba10 }
      
    public:
      eu-central-1a: { id: subnet-0939ed04e6646bd0d }
      eu-central-1b: { id: subnet-092d2e9f572efebf9 }
    

# eksctl create cluster -f eks-cluster-create.yaml