apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo1
  region: eu-central-1
  version: '1.21'

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-0751e6722a6fd51f0  }
      eu-central-1b: { id: subnet-019d86a1b60152405 }
      
    public:
      eu-central-1a: { id: subnet-0eddfa7c33f6eb916 }
      eu-central-1b: { id: subnet-0bb0c596c6db7b089 }
    

# eksctl create cluster -f eks-cluster-create.yaml